spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/auth/**
          filters:
            - name: RoleCheckerFilter
              args:
                isOpen: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    preferIpAddress: true

